export declare const PERMISSIONS: {
    readonly access_pos: "access_pos";
    readonly access_menu: "access_menu";
    readonly access_settings: "access_settings";
    readonly access_closure: "access_closure";
    readonly access_compliance: "access_compliance";
    readonly access_user_management: "access_user_management";
    readonly access_documents: "access_documents";
    readonly access_inbox: "access_inbox";
    readonly access_reservations: "access_reservations";
    readonly access_planning: "access_planning";
    readonly manage_floor_plan: "manage_floor_plan";
    readonly pos_happyhour_manual: "pos_happyhour_manual";
    readonly pos_apply_offert: "pos_apply_offert";
    readonly pos_apply_perso: "pos_apply_perso";
    readonly pos_reassign_waiter: "pos_reassign_waiter";
    readonly pos_intervene_table: "pos_intervene_table";
    readonly orders_cancel: "orders_cancel";
};
export type PermissionName = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
